WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600


CHARACTER_WIDTH = 20
CHARACTER_HEIGHT = 20
CHARACTER_COLOR = (255, 255, 0)
CHARACTER_SCALE = 1.8

BG_COLOR = (0, 28, 42)

FPS = 60

TILE_SIZE = 60  # Size of each tile in pixels
GRID_WIDTH = 6  # Width of the grid
GRID_HEIGHT = 6  # Height of the grid
MARGIN = 20  # Space around the map

SCREEN_SIZE = TILE_SIZE * max(GRID_WIDTH, GRID_HEIGHT) + 2 * MARGIN
